spring:
  application:
    name: user-service
  datasource:
    hikari.jdbc-url: jdbc:h2:mem:test_db;
    username: sa
    password:

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  h2:
    console:
      enabled: true

service:
  jwt:
    access-expiration: 21600000
    # secret-key: ${SECRET_KEY}
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"

# eureka server: 19090, gateway: 19091, user-service: 19092
eureka:
  client:
    service-url: # eureka-server 의 url 을 정의
      defaultZone: http://localhost:19090/eureka/ # 기본적으로 사용할 eureka-server 의 주소를 설정

server:
  port: 19092